# Generated by Django 5.2.5 on 2025-08-16 20:03

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature_forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('cv', models.FileField(max_length=255, upload_to='cv_candidats')),
                ('numero_telephone', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=255, upload_to='image_candidature')),
                ('presence', models.BooleanField(default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_forum', models.DateField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('recruteurs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('nombre_max', models.IntegerField()),
                ('qrcode', models.ImageField(upload_to='codes_QR')),
                ('date_debut', models.DateTimeField(blank=True, default=None, max_length=100, null=True)),
                ('date_fin', models.DateTimeField(blank=True, default=None, max_length=100, null=True)),
                ('duree', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Archive_talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidature', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_archive', to='App.candidature_forum')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=255)),
                ('annotation_candidat', models.IntegerField()),
                ('etat', models.CharField(max_length=100)),
                ('candidature', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_feedback', to='App.candidature_forum')),
            ],
        ),
        migrations.AddField(
            model_name='candidature_forum',
            name='forum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_candidature', to='App.forum'),
        ),
        migrations.CreateModel(
            name='Archive_forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_archive', to='App.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=255, upload_to='picturesrectruteur')),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='recruteur_set', related_query_name='recruteur_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='recruteur_permissions_set', related_query_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='universite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_universite', to='App.universite'),
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cv', models.FileField(max_length=255, upload_to='cv')),
                ('image', models.ImageField(max_length=255, upload_to='picturestalent')),
                ('email', models.CharField(max_length=150)),
                ('numero_telephone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', related_query_name='talent_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_archive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidature_forum',
            name='talent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='talent_candidature', to=settings.AUTH_USER_MODEL),
        ),
    ]
