# Generated by Django 5.2.5 on 2025-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_debut',
            field=models.TimeField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_fin',
            field=models.TimeField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
