# Generated by Django 5.2.5 on 2025-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_forum_date_debut_alter_forum_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature_forum',
            name='event_horaire',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
