# Generated by Django 5.2.5 on 2025-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_candidature_forum_event_horaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature_forum',
            name='event_horaire',
            field=models.CharField(null=True),
        ),
    ]
