# Generated by Django 5.2.5 on 2025-08-29 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_candidature_forum_event_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2025, 8, 29), max_length=100),
        ),
        migrations.AddField(
            model_name='recruteur',
            name='Entreprise',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
