# Generated by Django 5.2.5 on 2025-08-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_candidature_forum_date_inscri_recruteur_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='numero_telephone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
