# Generated by Django 5.2.5 on 2025-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_recruteur_numero_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteur',
            name='Entreprise',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
