# Generated by Django 5.2.5 on 2025-08-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_recruteur_entreprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruteur',
            old_name='Entreprise',
            new_name='entreprise',
        ),
    ]
