# Generated by Django 5.2.5 on 2025-08-30 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_entreprise_recruteur_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruteur',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='recruteur',
            name='numero_telephone',
        ),
        migrations.AlterField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2025, 8, 30), max_length=100),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
