# Generated by Django 5.2.5 on 2025-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_recruteur_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='entreprise',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recruteur',
            name='numero_telephone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
