# Generated by Django 5.2.5 on 2025-08-14 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-date_forum']},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='recruteurs',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='universite',
        ),
        migrations.AddField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_forum',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='duree',
            field=models.IntegerField(help_text='Duration in hours'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='qrcode_img',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
