# Generated by Django 5.2.5 on 2025-08-14 17:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_forum_options_remove_forum_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='forum',
            name='date_debut',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='date_fin',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='recruteurs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='forum',
            name='universite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_universite', to='App.universite'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_forum',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='forum',
            name='duree',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='qrcode_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
