# Generated by Django 5.2.5 on 2025-08-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_forum_options_remove_forum_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='qrcode_img',
            field=models.TextField(max_length=255),
        ),
    ]
