# Generated by Django 5.2.5 on 2025-08-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_forum_qrcode_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='qrcode_img',
            new_name='qrcode',
        ),
    ]
