# Generated by Django 5.2.5 on 2025-08-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_forum_date_debut_alter_forum_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='qrcode',
            field=models.ImageField(upload_to='codes_QR'),
        ),
    ]
