# Generated by Django 5.2.5 on 2025-08-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_forum_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
